---

- name: Set systemd version fact
  set_fact:
    apache_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Create apache_exporter systemd file
  template:
    src: apache_exporter.service.j2
    dest: /etc/systemd/system/apache_exporter.service
  notify: restart apache_exporter
